################################################################
# Authelia configuration
################################################################

server:
  host: 0.0.0.0
  port: 9091

totp:
  issuer: authelia.com

authentication_backend:
  file:
    path: /config/users.yaml

access_control:
  default_policy: one_factor

session:
  name: authelia_session
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt