################################################################
# Global configuration
################################################################
global:
  checkNewVersion: true
  sendAnonymousUsage: true

api:
  dashboard: true

################################################################
# EntryPoints configuration
################################################################

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443
    http:
      tls:
        certResolver: letsencrypt

################################################################
# Let's Encrypt configuration
################################################################

certificatesResolvers:
  letsencrypt:
    acme:
      storage: acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: cloudflare

################################################################
# Docker configuration backend
################################################################

providers:
  docker:
    exposedByDefault: false
    endpoint: tcp://socket-proxy:2375